const KEY = "korean-learn-state-v1";
const themes = ["rose", "mint", "sky", "apricot"];
const modules = [
  { id: 1, title: "韩文与第一声问候", desc: "字母、收音、你好与谢谢", threshold: 60, lessons: [
    { title:"元音与辅音", words:[{ko:"안녕하세요", roman:"annyeonghaseyo", zh:"您好 / 你好", note:"ㅇ在词首不发音；안녕后与하세요连读。"},{ko:"감사합니다", roman:"gamsahamnida", zh:"谢谢", note:"ㅂ在ㅂ니다中接近 [m]，听感像 감삼니다。"},{ko:"네", roman:"ne", zh:"是 / 好", note:"简短回应，元音清晰。"}] },
    { title:"礼貌地告别", words:[{ko:"안녕히 가세요", roman:"annyeonghi gaseyo", zh:"再见（对离开的人）", note:"ㅎ在连读中较轻。"},{ko:"안녕히 계세요", roman:"annyeonghi gyeseyo", zh:"再见（对留下的人）", note:"계读作 gye。"},{ko:"죄송합니다", roman:"joesonghamnida", zh:"对不起", note:"ㅚ现代常读接近 we。"}] }
  ]},
  { id: 2, title: "认识彼此", desc: "自我介绍与礼貌回应", threshold: 65, lessons: [
    { title:"说出你的名字", words:[{ko:"저는",roman:"jeoneun",zh:"我是（礼貌）",note:"는为主题助词。"},{ko:"이름",roman:"ireum",zh:"名字",note:"름末尾的ㅁ闭唇收音。"},{ko:"만나서 반갑습니다",roman:"mannaseo bangapseumnida",zh:"很高兴见到您",note:"ㅂ在습니다前听起来接近 [p]。"}] },
    { title:"简单问答", words:[{ko:"어디에서 왔어요?",roman:"eodieseo wasseoyo?",zh:"您从哪里来？",note:"왔어요中ㅆ为收音。"},{ko:"중국에서 왔어요",roman:"junggugeseo wasseoyo",zh:"我从中国来",note:"국与에连读时收音变为 [g]。"},{ko:"한국어를 배워요",roman:"hangugeo-reul baewoyo",zh:"我学韩语",note:"어를自然连读。"}] }
  ]},
  { id: 3, title: "吃喝点餐", desc: "餐厅、饮料与结账", threshold: 70, lessons: [
    { title:"在餐厅开口", words:[{ko:"메뉴 주세요",roman:"menyu juseyo",zh:"请给我菜单",note:"주세요是常用的“请给我”。"},{ko:"이거 주세요",roman:"igeo juseyo",zh:"请给我这个",note:"指着物品时很实用。"},{ko:"물 주세요",roman:"mul juseyo",zh:"请给我水",note:"ㄹ为收音，舌尖收住。"}] },
    { title:"结账与口味", words:[{ko:"계산해 주세요",roman:"gyesan-hae juseyo",zh:"请结账",note:"계산的ㅅ在元音前读 [s]。"},{ko:"맛있어요",roman:"masisseoyo",zh:"很好吃",note:"있与어요连读，ㅆ发紧音感。"},{ko:"안 매워요",roman:"an maewoyo",zh:"不辣",note:"ㄴ与ㅁ相邻，顺滑连读。"}] }
  ]},
  { id: 4, title: "住宿与交通", desc: "入住、问路、乘车", threshold: 75, lessons: [
    { title:"办理入住", words:[{ko:"예약했어요",roman:"yeyakhaesseoyo",zh:"我预订了",note:"했어요的ㅎ较弱。"},{ko:"체크인하고 싶어요",roman:"chekeu-inhago sipeoyo",zh:"我想办理入住",note:"外来词按节奏清晰读。"},{ko:"와이파이 있어요?",roman:"waipai isseoyo?",zh:"有 Wi‑Fi 吗？",note:"있어요末尾自然连读。"}] },
    { title:"问路与乘车", words:[{ko:"지하철역이 어디예요?",roman:"jihacheol-yeogi eodiyeyo?",zh:"地铁站在哪里？",note:"역이连接时ㄱ变为 [g]。"},{ko:"여기로 가 주세요",roman:"yeogiro ga juseyo",zh:"请去这里",note:"出租车指路常用。"},{ko:"내려 주세요",roman:"naeryeo juseyo",zh:"请让我下车",note:"려发 ryeo。"}] }
  ]},
  { id: 5, title: "紧急情况与复盘", desc: "求助、复习与生活对话", threshold: 80, lessons: [
    { title:"需要帮助时", words:[{ko:"도와주세요",roman:"dowajuseyo",zh:"请帮帮我",note:"와与주连贯读出。"},{ko:"화장실이 어디예요?",roman:"hwajangsil-i eodiyeyo?",zh:"洗手间在哪里？",note:"실이中ㄹ与元音连读。"},{ko:"천천히 말해 주세요",roman:"cheoncheonhi malhae juseyo",zh:"请说慢一点",note:"ㅎ较轻但保留节奏。"}] },
    { title:"最后的生活表达", words:[{ko:"괜찮아요",roman:"gwaenchanayo",zh:"没关系 / 可以",note:"ㅙ现代常接近 we。"},{ko:"얼마예요?",roman:"eolmayeyo?",zh:"多少钱？",note:"얼的ㄹ收音要收住。"},{ko:"카드 돼요?",roman:"kadeu dwaeyo?",zh:"可以刷卡吗？",note:"돼요读 dwaeyo。"}] }
  ]}
];

const quizBank = [
  {type:"choice",prompt:"‘감사합니다’ 的意思是？",answer:"谢谢",options:["对不起","谢谢","再见","没关系"],word:"감사합니다"},
  {type:"choice",prompt:"‘请给我菜单’ 的韩语是？",answer:"메뉴 주세요",options:["물 주세요","메뉴 주세요","계산해 주세요","도와주세요"],word:"메뉴 주세요"},
  {type:"input",prompt:"请输入“你好”的韩语。",answer:"안녕하세요",word:"안녕하세요"},
  {type:"choice",prompt:"‘지하철역이 어디예요?’ 的意思是？",answer:"地铁站在哪里？",options:["洗手间在哪里？","地铁站在哪里？","多少钱？","有 Wi‑Fi 吗？"],word:"지하철역이 어디예요?"},
  {type:"input",prompt:"请输入“请帮帮我”的韩语。",answer:"도와주세요",word:"도와주세요"}
];

function freshState() { return { current:1, completed:[], scores:{}, mistakes:[], dailyMinutes:0, lastDate:"", lang:"zh", scheme:"system", theme:themes[Math.floor(Math.random()*themes.length)], onboarding:true }; }
let state; try { state = {...freshState(), ...JSON.parse(localStorage.getItem(KEY))}; } catch { state=freshState(); }
let view = "home", lessonIndex = 0, quiz = null;
function save(){ localStorage.setItem(KEY, JSON.stringify(state)); }
function esc(text){ return String(text).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c])); }
function t(zh,ko){ return state.lang === "ko" ? ko : zh; }
function applyTheme(){ document.documentElement.dataset.theme = state.theme === "rose" ? "" : state.theme; document.documentElement.dataset.scheme = state.scheme === "system" ? (matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light") : state.scheme; }
function mastered(){ return state.completed.length; }
function currentModule(){ return modules.find(m=>m.id===state.current) || modules[0]; }
function addMinutes(n=10){ const today=new Date().toISOString().slice(0,10); if(state.lastDate!==today){state.dailyMinutes=0;state.lastDate=today;} state.dailyMinutes=Math.min(10,state.dailyMinutes+n); save(); }
function speak(text){ if(!("speechSynthesis" in window)){ alert("此浏览器不支持语音合成。请尝试使用 Edge，或安装系统韩语语音。"); return; } const u=new SpeechSynthesisUtterance(text); u.lang="ko-KR"; u.rate=.8; const voices=speechSynthesis.getVoices(); const ko=voices.find(v=>v.lang.toLowerCase().startsWith("ko")); if(ko) u.voice=ko; speechSynthesis.cancel(); speechSynthesis.speak(u); }
function nav(){ return `<header class="topbar"><div class="brand"><span class="brand-mark">ㅎ</span><span>Korean-learn</span></div><nav class="nav"><button class="${view==='home'?'active':''}" data-nav="home">${t("学习","학습")}</button><button class="${view==='progress'?'active':''}" data-nav="progress">${t("进度","진도")}</button><button class="${view==='settings'?'active':''}" data-nav="settings">${t("设置","설정")}</button></nav></header>`; }
function home(){ const m=currentModule(), pct=Math.round(mastered()/modules.length*100); return `<main><section class="hero card"><div class="eyebrow">${t("10 分钟，继续向前","10분, 계속 앞으로")}</div><h1>${t("今天，学会一句真正能说出口的韩语。","오늘, 실제로 말할 수 있는 한국어 한 문장.")}</h1><p class="muted">${t("从拼读到韩国短期生活对话。每个模块通过考核后才会解锁下一步。","읽기부터 한국 생활 대화까지. 평가를 통과하면 다음 모듈이 열립니다.")}</p><div class="hero-actions"><button class="btn primary" data-action="continue">${t("继续本模块","이 모듈 계속하기")}</button><button class="btn" data-action="install-help">${t("离线使用说明","오프라인 안내")}</button></div></section><section class="section"><div class="section-head"><h2>${t("今日学习","오늘의 학습")}</h2><span class="muted small">${t("目标 10 分钟","목표 10분")}</span></div><div class="today card"><div><h3>${m.title}</h3><p class="muted small">${m.desc}</p><div class="progress-track"><span style="width:${pct}%"></span></div></div><div class="ring" style="--progress:${state.dailyMinutes*10}%"><b>${state.dailyMinutes}/10</b></div></div></section><section class="section"><div class="section-head"><h2>${t("学习路径","학습 경로")}</h2><span class="muted small">${mastered()}/${modules.length} ${t("完成","완료")}</span></div><div class="module-grid">${modules.map(m=>moduleCard(m)).join("")}</div></section></main>`; }
function moduleCard(m){ const done=state.completed.includes(m.id), locked=m.id>state.current; return `<article class="module card ${locked?'locked':''}"><div class="module-number">MODULE ${m.id}</div><h3 class="module-title">${esc(m.title)}</h3><p class="muted small">${esc(m.desc)}</p><div class="module-meta"><span>${m.lessons.length*10} ${t("分钟","분")}</span><span>${t("通过线","통과선")} ${m.threshold}</span></div><span class="badge">${done?t("已通过","통과"):(locked?t("待解锁","잠김"):t("进行中","학습 중"))}</span></article>`; }
function lesson(){ const m=currentModule(), l=m.lessons[lessonIndex % m.lessons.length]; return `<main><section class="lesson card"><div class="lesson-top"><button class="btn ghost" data-nav="home">← ${t("返回","뒤로")}</button><span class="muted small">${t("模块","모듈")} ${m.id} · ${lessonIndex+1}/${m.lessons.length}</span></div><div class="eyebrow">${esc(l.title)}</div><h1>${esc(m.title)}</h1><p class="muted">${t("先听，再看，再自己读一遍。","먼저 듣고, 보고, 직접 읽어 보세요.")}</p><div class="word-list">${l.words.map((w,i)=>`<div class="word-item"><div><div class="korean"><strong>${esc(w.ko)}</strong> <span class="roman">${esc(w.roman)}</span></div><div>${esc(w.zh)}</div><div class="small muted">${t("发音提示：","발음 팁: ")}${esc(w.note)}</div></div><button class="speaker" aria-label="播放 ${esc(w.ko)}" data-speak="${esc(w.ko)}">▶</button></div>`).join("")}</div><div class="pronunciation"><strong>${t("跟读建议：","따라 읽기: ")}</strong>${t("先按词组慢读，再连续读两遍；浏览器若未安装韩语语音，会使用系统默认声音。","먼저 천천히 읽고, 이어서 두 번 읽어 보세요.")}</div><div class="actions"><button class="btn" data-action="prev-lesson" ${lessonIndex===0?'disabled':''}>${t("上一单元","이전")}</button><button class="btn primary" data-action="next-lesson">${lessonIndex+1<m.lessons.length?t("完成并继续","완료하고 계속"):`${t("开始模块考核","모듈 평가 시작")}`}</button></div></section></main>`; }
function progress(){ const pct=Math.round(mastered()/modules.length*100), mistakes=[...new Set(state.mistakes)].slice(-6); return `<main><section class="hero card"><div class="eyebrow">${t("你的学习足迹","학습 기록")}</div><h1>${pct}% ${t("已完成","완료")}</h1><div class="progress-track"><span style="width:${pct}%"></span></div></section><section class="section stat-grid"><article class="stat card"><span class="muted small">${t("已通过模块","통과한 모듈")}</span><strong>${mastered()} / ${modules.length}</strong></article><article class="stat card"><span class="muted small">${t("今日学习","오늘 학습")}</span><strong>${state.dailyMinutes} ${t("分钟","분")}</strong></article><article class="stat card"><span class="muted small">${t("最近成绩","최근 점수")}</span><strong>${Object.values(state.scores).at(-1) ?? "—"}</strong></article></section><section class="section card lesson"><h2>${t("需要复习","복습할 단어")}</h2>${mistakes.length?`<ul class="mistake-list">${mistakes.map(w=>`<li><span class="korean">${esc(w)}</span><button class="speaker" data-speak="${esc(w)}">▶</button></li>`).join("")}</ul>`:`<div class="empty muted">${t("完成一次考核后，易错词会出现在这里。","평가 후 틀린 단어가 여기에 표시됩니다.")}</div>`}</section></main>`; }
function settings(){ return `<main><section class="settings card"><h1>${t("设置","설정")}</h1><div class="setting-row"><div><h3>${t("讲解语言","설명 언어")}</h3><span class="muted small">${t("可随时切换中韩显示。","중국어와 한국어를 전환합니다.")}</span></div><div class="segmented"><button data-lang="zh" class="${state.lang==='zh'?'active':''}">中文</button><button data-lang="ko" class="${state.lang==='ko'?'active':''}">한국어</button></div></div><div class="setting-row"><div><h3>${t("显示模式","화면 모드")}</h3><span class="muted small">${t("默认跟随系统，也可手动选择。","기본은 시스템 설정입니다.")}</span></div><div class="segmented"><button data-scheme="system" class="${state.scheme==='system'?'active':''}">${t("自动","자동")}</button><button data-scheme="light" class="${state.scheme==='light'?'active':''}">${t("浅色","밝게")}</button><button data-scheme="dark" class="${state.scheme==='dark'?'active':''}">${t("深色","어둡게")}</button></div></div><div class="setting-row"><div><h3>${t("主题色","테마 색")}</h3><span class="muted small">${t("每次打开会随机选择一套协调配色。","열 때마다 색상이 바뀝니다.")}</span></div><button class="btn" data-action="new-theme">${t("换一种","바꾸기")}</button></div><div class="setting-row"><div><h3>${t("本机数据","내 기기 데이터")}</h3><span class="muted small">${t("学习进度仅保存在当前浏览器。","학습 기록은 이 브라우저에만 저장됩니다.")}</span></div><button class="btn" data-action="reset">${t("重置进度","초기화")}</button></div></section></main>`; }
function assessment(){ const q=quiz.questions[quiz.index]; const body=q.type==='choice'?`<div>${q.options.map(o=>`<button class="quiz-option" data-answer="${esc(o)}">${esc(o)}</button>`).join("")}</div>`:`<div><input class="answer-input korean" id="answer" autocomplete="off" placeholder="${t("使用韩语键盘输入","한국어 키보드로 입력")}" /><div class="actions"><button class="btn primary" data-action="submit-input">${t("提交答案","답 제출")}</button></div></div>`; return `<main><section class="lesson card"><div class="lesson-top"><button class="btn ghost" data-nav="home">← ${t("退出","나가기")}</button><span class="muted small">${t("模块考核","모듈 평가")} ${quiz.index+1}/${quiz.questions.length}</span></div><div class="eyebrow">${currentModule().title}</div><h1>${t("检验一下掌握情况","실력을 확인해 볼까요?")}</h1><p class="muted">${t("通过线","통과선")} ${currentModule().threshold} ${t("分","점")}</p><div class="notice">${esc(q.prompt)} ${q.type==='choice'?`<button class="speaker" data-speak="${esc(q.word)}">▶</button>`:""}</div>${body}<div id="feedback" class="feedback" aria-live="polite"></div></section></main>`; }
function results(){ const pass=quiz.score>=currentModule().threshold, m=currentModule(); return `<main><section class="hero card"><div class="eyebrow">${pass?t("模块通过","모듈 통과"):t("再复习一次","다시 복습")}</div><h1>${quiz.score} ${t("分","점")}</h1><p class="muted">${pass?t("你已达到本模块的掌握标准，下一模块现在解锁。","다음 모듈이 열렸습니다."):t("错题已加入复习清单。复习后可以再次考核。","틀린 단어가 복습 목록에 추가되었습니다.")}</p><div class="actions"><button class="btn primary" data-nav="home">${pass?t("查看下一模块","다음 모듈 보기"):t("回到模块复习","모듈 복습")}</button><button class="btn" data-nav="progress">${t("查看进度","진도 보기")}</button></div></section></main>`; }
function render(){ applyTheme(); let content=view==='home'?home():view==='lesson'?lesson():view==='progress'?progress():view==='settings'?settings():view==='assessment'?assessment():results(); document.querySelector('#app').innerHTML=`<div class="shell">${nav()}${content}</div>`; attach(); }
function startAssessment(){ const offset=(state.current-1)%2; quiz={index:0,score:0,questions:[...quizBank.slice(0,3),quizBank[3+offset],quizBank[4]]}; view='assessment'; render(); }
function check(answer){ const q=quiz.questions[quiz.index], correct=answer.trim()===q.answer; const feedback=document.querySelector('#feedback'); document.querySelectorAll('[data-answer]').forEach(b=>{ b.disabled=true; if(b.dataset.answer===q.answer)b.classList.add('correct'); else if(b.dataset.answer===answer)b.classList.add('wrong'); }); if(correct){quiz.score+=20;feedback.textContent=t('正确！','맞았습니다!');feedback.className='feedback good';} else {state.mistakes.push(q.word);save();feedback.textContent=`${t('正确答案：','정답: ')}${q.answer}`;feedback.className='feedback bad';} setTimeout(()=>{quiz.index++; if(quiz.index>=quiz.questions.length){ const m=currentModule(); state.scores[m.id]=quiz.score; if(quiz.score>=m.threshold&&!state.completed.includes(m.id)){state.completed.push(m.id); state.current=Math.min(modules.length,m.id+1);} save(); view='results'; } render();},900); }
function attach(){ document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;render();}); document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak)); document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;save();render();}); document.querySelectorAll('[data-scheme]').forEach(b=>b.onclick=()=>{state.scheme=b.dataset.scheme;save();render();}); document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>check(b.dataset.answer)); const act=(name,fn)=>{const el=document.querySelector(`[data-action="${name}"]`);if(el)el.onclick=fn;}; act('continue',()=>{lessonIndex=0;view='lesson';render();}); act('prev-lesson',()=>{lessonIndex--;render();}); act('next-lesson',()=>{addMinutes(); if(lessonIndex+1<currentModule().lessons.length){lessonIndex++;render();}else startAssessment();}); act('submit-input',()=>{const input=document.querySelector('#answer');if(input)check(input.value);}); act('new-theme',()=>{state.theme=themes[(themes.indexOf(state.theme)+1)%themes.length];save();render();}); act('reset',()=>{if(confirm(t('确定重置当前浏览器中的所有学习记录吗？','학습 기록을 초기화할까요?'))){state=freshState();save();render();}}); act('install-help',()=>alert(t('离线使用：首次打开后，在浏览器菜单中选择“安装应用”或“添加到主屏幕”。请先在设备设置中启用韩语键盘。学习进度只保存在当前浏览器。','브라우저 메뉴에서 앱 설치 또는 홈 화면에 추가를 선택하세요. 한국어 키보드를 먼저 켜 주세요.'))); }
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
